### ISSUE TITLE
clojure.set/ shows clojure.set/index

### ISSUE THREAD

**Issue by eval** [cljs/api#194]
Visiting [clojure.set](https://cljs.github.io/api/clojure.set/) won't show the overview of the namespace (like with e.g. [clojure.edn](https://cljs.github.io/api/clojure.edn/)), but clojure.set/index instead, as that's a var 😃

**Comment by shaunlebron** [comment]
Ayeee, I really need to fix this. https://github.com/cljs/site/issues/27  Thanks!

**Comment by eval** [comment]
Ah, already on the list :) closing this one!
